"""Added chat models Final

Revision ID: f8e67012fc3d
Revises: 9012f47b7322
Create Date: 2025-02-17 12:13:08.707569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f8e67012fc3d'
down_revision: Union[str, None] = '9012f47b7322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversationparticipants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conv_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conv_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversationparticipants_conv_id'), 'conversationparticipants', ['conv_id'], unique=False)
    op.create_index(op.f('ix_conversationparticipants_user_id'), 'conversationparticipants', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('conv_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conv_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conv_id'), 'messages', ['conv_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conv_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversationparticipants_user_id'), table_name='conversationparticipants')
    op.drop_index(op.f('ix_conversationparticipants_conv_id'), table_name='conversationparticipants')
    op.drop_table('conversationparticipants')
    op.drop_table('conversation')
    # ### end Alembic commands ###
