"""added is_group

Revision ID: ff43fa492d79
Revises: f8e67012fc3d
Create Date: 2025-02-17 15:10:01.589868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff43fa492d79'
down_revision: Union[str, None] = 'f8e67012fc3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('is_group', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'is_group')
    # ### end Alembic commands ###
